// src/app/layout.js
import "./globals.css";
import Sidebar from "./sidebar"; // Sidebar bileşeni, prefetching işlevini içeriyor
import Providers from "./providers"; // React Query global provider

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          <Sidebar>{children}</Sidebar>
        </Providers>
      </body>
    </html>
  );
}
